FROM python:3.10-slim-bullseye

ARG TZ='Asia/Shanghai'

ARG CHATGPT_ON_WECHAT_VER
ARG APT_MIRROR=''
USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV BUILD_PREFIX=/app

RUN if [ -n "${APT_MIRROR}" ] && [ -f /etc/apt/sources.list ]; then \
        sed -i "s|deb.debian.org|${APT_MIRROR}|g" /etc/apt/sources.list; \
        sed -i "s|security.debian.org|${APT_MIRROR}|g" /etc/apt/sources.list; \
    fi \
 && apt-get update --fix-missing \
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg \
 && rm -rf /var/lib/apt/lists/*



ADD . ${BUILD_PREFIX}


RUN cd ${BUILD_PREFIX} \
    && cp config-template.json config.json \
    && /usr/local/bin/python -m pip install --no-cache-dir uv
    # -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

WORKDIR ${BUILD_PREFIX}

# ADD docker/entrypoint.sh /entrypoint.sh

# 开发环境卓nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update \
    && apt-get install -y --no-install-recommends nodejs \
    && npm install -g @openai/codex@latest \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /root/.codex
ADD ./config.toml /root/.codex/config.toml
